spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/timetabbble
        username: bebrik
        password: bebrabebra
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
---
spring:
    profiles:
        active: dev
    application:
        name: "Demo"
        version: "0.1"
---
jwt:
    secret: 6a627a7fb025e2c5db643267523a1c801c1178bed30331a2606fe93f4dd9aa7b
    access:
        duration:
            minutes: 5
            seconds: 300
        cookie-name: access_token
    refresh:
        duration:
            days: 7
            seconds: 604800
        cookie-name: refresh_token