spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
---
spring:
    profiles:
        active: dev
    application:
        name: "Demo"
        version: "0.1"
---
jwt:
    secret: ${JWT_SECRET}
    access:
        duration:
            minutes: 5
            seconds: 300
        cookie-name: access_token
    refresh:
        duration:
            days: 7
            seconds: 604800
        cookie-name: refresh_token
---
logging:
    file:
        name: logs/application.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n"
---
spring:
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
            max-request-size: 10MB
            enabled: true
---
telegram:
    bot:
        name: ${BOT_NAME}
        token: ${BOT_TOKEN}
        chatId: ${BOT_CHATID}
---
report:
    template-location: classpath:templates/student-deadlines-report-template.xlsx
---
springdoc:
    api-docs:
        path: /v3/api-docs
        enabled: true
    swagger-ui:
        path: /swagger-ui
        enabled: true
        tags-sorter: alpha
        operations-sorter: method
        display-request-duration: true
        default-model-expand-depth: 2
        default-models-expand-depth: 2
        try-it-out-enabled: true
    show-actuator: false
    packages-to-scan: com.example.demo.controller